apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1  # You may want to specify the number of replicas
  selector:    # A selector is needed to match the pods
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - name: synergychat-crawler
        image: bootdotdev/synergychat-crawler:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: synergychat-crawler-configmap


